mysql:
  user: root
  pwd: '@QQ219zoing'
  host: localhost
  port: 3306
  dbname: magic_space
video:
  path: /usr/local/nginx/html/video
email:
  user: magic_space_leo@163.com
  pwd: LLKZPTUFPETNUWDY
  host: smtp.163.com
  port: 465
host:
  name: http://localhost
  port: 4011